stages:
  - test

unit_tests:
  stage: test
  tags:
    - shell
  when: manual
  script:
    # - sudo apt-get update -y
    # - sudo apt-get install -y libpq-dev
    # - sudo cd /home/ubuntu/twitter-clone-myApp
    # - sudo source source env-twitter/bin/activate
    # - sudo pip install -r requirements.txt
    - sudo python manage.py test/

  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml