stages:
  - test

 

unit_tests:
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y libpq-dev
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python manage.py test
  artifacts:
    when: manual
    paths:
      - junit.xml
    reports:
      junit: junit.xml